services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    container_name: mailpit
    ports:
      - '1025:1025'   # SMTP — сюда стучится nodemailer
      - '8025:8025'   # веб-морда — сюда стучишься ты браузером

volumes:
  postgres_data:
  cache:
    driver: local